### ISSUE TITLE
Cannot read property 'lat' of null TypeError: Cannot read property 'lat' of null

### ISSUE THREAD

**Issue by Un1matr1x** [abakedapplepie/RealDeviceMap-tools#17]
Hi,

this tool worked like charme till today, didn't change a bit, but today the page keeped blank, consol output:

`jquery.min.js:2 jQuery.Deferred exception: Cannot read property 'lat' of null TypeError: Cannot read property 'lat' of null
    at Object.project (https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.4/leaflet.js:5:24364)
    at Object.latLngToPoint (https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.4/leaflet.js:5:23003)
    at e.project (https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.4/leaflet.js:5:39368)
    at e._getNewPixelOrigin (https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.4/leaflet.js:5:45470)
    at e._move (https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.4/leaflet.js:5:42126)
    at e._resetView (https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.4/leaflet.js:5:41836)
    at e.setView (https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.4/leaflet.js:5:30590)
    at initMap (http://192.168.178.23:8080/rdm-tools.php:261:45)
    at HTMLDocument.<anonymous> (http://192.168.178.23:8080/rdm-tools.php:124:3)
    at l (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:29375) undefined
w.Deferred.exceptionHook @ jquery.min.js:2
jquery.min.js:2 Uncaught TypeError: Cannot read property 'lat' of null
    at Object.project (leaflet.js:5)
    at Object.latLngToPoint (leaflet.js:5)
    at e.project (leaflet.js:5)
    at e._getNewPixelOrigin (leaflet.js:5)
    at e._move (leaflet.js:5)
    at e._resetView (leaflet.js:5)
    at e.setView (leaflet.js:5)
    at initMap (rdm-tools.php:261)
    at HTMLDocument.<anonymous> (rdm-tools.php:124)
    at l (jquery.min.js:2)
13leaflet.js:5 Uncaught TypeError: Cannot read property 'x' of undefined
    at x._add (leaflet.js:5)
    at x.add (leaflet.js:5)
    at e.layerPointToLatLng (leaflet.js:5)
    at e._fireDOMEvent (leaflet.js:5)
    at e._handleDOMEvent (leaflet.js:5)
    at HTMLDivElement.r (leaflet.js:5)
leaflet.js:5 Uncaught TypeError: Cannot read property 'x' of undefined
    at x._add (leaflet.js:5)
    at x.add (leaflet.js:5)
    at e.layerPointToLatLng (leaflet.js:5)
    at e.getCenter (leaflet.js:5)
    at e.<anonymous> (leaflet.js:5)
    at e.fire (leaflet.js:5)
leaflet.js:5 Uncaught TypeError: Cannot read property 'x' of undefined
    at x._add (leaflet.js:5)
    at x.add (leaflet.js:5)
    at e.layerPointToLatLng (leaflet.js:5)
    at e._fireDOMEvent (leaflet.js:5)
    at e._handleDOMEvent (leaflet.js:5)
    at HTMLDivElement.r (leaflet.js:5)
leaflet.js:5 Uncaught TypeError: Cannot read property 'x' of undefined
    at x._add (leaflet.js:5)
    at x.add (leaflet.js:5)
    at e.layerPointToLatLng (leaflet.js:5)
    at e.getCenter (leaflet.js:5)
    at e.<anonymous> (leaflet.js:5)
    at e.fire (leaflet.js:5)
4leaflet.js:5 Uncaught TypeError: Cannot read property 'x' of undefined
    at x._add (leaflet.js:5)
    at x.add (leaflet.js:5)
    at e.layerPointToLatLng (leaflet.js:5)
    at e._fireDOMEvent (leaflet.js:5)
    at e._handleDOMEvent (leaflet.js:5)
    at HTMLDivElement.r (leaflet.js:5)
leaflet.js:5 Uncaught TypeError: Cannot read property 'x' of undefined
    at x._add (leaflet.js:5)
    at x.add (leaflet.js:5)
    at e.layerPointToLatLng (leaflet.js:5)
    at e._touchEvent (leaflet.draw.js:9)
    at e._onTouchStart (leaflet.draw.js:9)
    at r (leaflet.js:5)
    at j (leaflet.js:5)
    at leaflet.js:5
15leaflet.js:5 Uncaught TypeError: Cannot read property 'x' of undefined
    at x._add (leaflet.js:5)
    at x.add (leaflet.js:5)
    at e.layerPointToLatLng (leaflet.js:5)
    at e._fireDOMEvent (leaflet.js:5)
    at e._handleDOMEvent (leaflet.js:5)
    at HTMLDivElement.r (leaflet.js:5)
leaflet.js:5 Uncaught TypeError: Cannot read property 'x' of undefined
    at x._add (leaflet.js:5)
    at x.add (leaflet.js:5)
    at e.layerPointToLatLng (leaflet.js:5)
    at e.getCenter (leaflet.js:5)
    at e.<anonymous> (leaflet.js:5)
    at e.fire (leaflet.js:5)
_add @ leaflet.js:5
add @ leaflet.js:5
layerPointToLatLng @ leaflet.js:5
getCenter @ leaflet.js:5
(anonymous) @ leaflet.js:5
fire @ leaflet.js:5
65leaflet.js:5 Uncaught TypeError: Cannot read property 'x' of undefined
    at x._add (leaflet.js:5)
    at x.add (leaflet.js:5)
    at e.layerPointToLatLng (leaflet.js:5)
    at e._fireDOMEvent (leaflet.js:5)
    at e._handleDOMEvent (leaflet.js:5)
    at HTMLDivElement.r (leaflet.js:5)
_add @ leaflet.js:5
add @ leaflet.js:5
layerPointToLatLng @ leaflet.js:5
_fireDOMEvent @ leaflet.js:5
_handleDOMEvent @ leaflet.js:5
r @ leaflet.js:5`

**Comment by Un1matr1x** [comment]
tested with GoogleChrome - output see above
tested with Firefox - works fine
